# SPDX-License-Identifier: GPL-2.0
# MakeFile for CameraLink in and FX3 DMA drivers

obj-$(CONFIG_QUEST_DMA) += qdma_clink.o
qdma_clink-objs := quest_clink_in_dma.o quest_dma_core.o

obj-$(CONFIG_QUEST_DMA) += qdma_fx3.o
qdma_fx3-objs := quest_fx3_dma.o quest_dma_core.o
